### ISSUE TITLE
mx spacing homing keys

### ISSUE THREAD

**Issue by ShannonMasters** [braindefender/vardera-kailh-choc-keycaps#1]
Any chance of you adding MX spaced homing keys?  I was really interested in trying these out, until I realised there's only MX spaced normal and thumb keys.

I honestly have no idea how to modify the 3d files myself, so I'm otherwise lost here.

**Comment by braindefender** [comment]
Sorry, but the project is no longer maintained. You can try [KLP Lame Keycaps](https://github.com/braindefender/KLP-Lame-Keycaps) or, perhaps, find someone who edit 3D files for you.

**Comment by ShannonMasters** [comment]
thanks for the response, I already have KLP Lame keycaps printed, but they're also choc spaced and not MX.

No worries, thanks anyway.
